import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="hidden lg:block absolute right-[-160px] top-[-200px] -z-10">
        <img src="/bg-tablet-pattern.svg" alt="" />
      </div>

      <header className="lg:flex items-center max-w-6xl w-11/12 mx-auto py-8">
        <div className="flex-1 mb-10 lg:mb-0">
          <h3 className="text-4xl lg:text-6xl font-bold text-DarkBlue">
            Bring everyone together to build better products.
          </h3>
          <p className="w-full lg:w-8/12 text-DarkGrayishBlue mt-6">
            Manage makes it simple for software teams to plan day-to-day tasks
            while keeping the larger team goals in view.
          </p>
        </div>
        <div className="flex flex-1 justify-center">
          <div>
            <img src="/illustration-intro.svg" alt="" className="" />
          </div>
        </div>
      </header>
    </div>
  );
};

export default Home;
