import React from "react";
import Head from "next/head";
import Link from "next/link";
import Navbar from "../components/Navbar";
import { GET_HEADER_HOME } from "../graphql/queries/headerHome";
import client from "../config/apollo";
import { GET_GROWTH_HOME } from "../graphql/queries/growthHome";

export const getStaticProps = async () => {
  const { data: headerData } = await client.query({
    query: GET_HEADER_HOME,
  });

  const { data: growthData } = await client.query({
    query: GET_GROWTH_HOME,
  });

  return {
    props: {
      headerData,
      growthData,
    },
  };
};

const Home = ({
  headerData,
  growthData,
}: {
  headerData: any;
  growthData: any;
}) => {
  const headerHomeData = headerData?.getHeaderHome;
  const growthHomeData = growthData?.getGrowthHome;

  return (
    <>
      <Head>
        <title>Landing Manage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <Navbar />

      <div className="hidden lg:block absolute right-[-160px] top-[-200px] -z-10">
        <img src="/bg-tablet-pattern.svg" alt="" />
      </div>

      <header className="lg:flex items-center max-w-6xl w-11/12 mx-auto py-8">
        <div className="flex-1 mb-10 lg:mb-0">
          <h3 className="text-4xl lg:text-6xl font-bold text-DarkBlue">
            {headerHomeData?.title}
          </h3>
          {headerHomeData?.description.map((item: any) => (
            <p
              key={item.id}
              className="w-full lg:w-8/12 text-DarkGrayishBlue mt-6"
            >
              {item.text}
            </p>
          ))}
        </div>
        <div className="flex flex-1 justify-center">
          <div>
            <img src={headerHomeData?.image} alt="" className="" />
          </div>
        </div>
      </header>

      <section className="max-w-6xl mx-auto w-11/12 lg:flex items-start py-8 lg:py-16">
        <div className="flex-1">
          <h3 className="text-2xl lg:text-4xl font-bold text-DarkBlue">
            {growthHomeData?.title}
          </h3>
          {growthHomeData.description.map((item: any) => (
            <p
              key={item.id}
              className="w-full lg:w-8/12 text-DarkGrayishBlue mt-6"
            >
              {item.text}
            </p>
          ))}
        </div>
        <div className="flex-1 mt-8">
          {growthHomeData.items.map((item: any) => (
            <article
              key={item.id}
              className="grid grid-cols-[60px_1fr] items-center mb-10 gap-x-4"
            >
              <div className="bg-BrightRed text-white py-2 px-4 rounded-2xl text-center text-xs font-bold">
                0{item.id}
              </div>
              <div className="text-DarkBlue font-semibold">{item.title}</div>
              <div className="col-start-1 lg:col-start-2 col-end-5 mt-3 text-DarkGrayishBlue">
                {item.description.map((item: any) => (
                  <span key={item.id}>{item.text}</span>
                ))}
              </div>
            </article>
          ))}
        </div>
      </section>

      <section className="max-w-6xl w-11/12 mx-auto text-2xl lg:text-4xl font-bold text-DarkBlue py-8">
        <h3 className="text-center">What they`ve said</h3>

        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-x-10 gap-y-20 mt-20">
          <article className="rounded-xl bg-gray p-4">
            <div className="grid place-items-center py-4">
              <img
                src="/avatar-anisha.png"
                alt=""
                className="w-32 mt-[-80px]"
              />
            </div>
            <h4 className="text-lg text-center">Anisha Li</h4>
            <p className="text-base font-normal text-DarkGrayishBlue mt-2 text-center">
              “Manage has supercharged our team’s workflow. The ability to
              maintain visibility on larger milestones at all times keeps
              everyone motivated.”
            </p>
          </article>
          <article className="rounded-xl bg-gray p-4">
            <div className="grid place-items-center py-4">
              <img src="/avatar-ali.png" alt="" className="w-32 mt-[-80px]" />
            </div>
            <h4 className="text-lg text-center">Ali Bravo</h4>
            <p className="text-base font-normal text-DarkGrayishBlue mt-2 text-center">
              “We have been able to cancel so many other subscriptions since
              using Manage. There is no more cross-channel confusion and
              everyone is much more focused.”
            </p>
          </article>
          <article className="rounded-xl bg-gray p-4">
            <div className="grid place-items-center py-4">
              <img
                src="/avatar-richard.png"
                alt=""
                className="w-32 mt-[-80px]"
              />
            </div>
            <h4 className="text-lg text-center">Richard Watts</h4>
            <p className="text-base font-normal text-DarkGrayishBlue mt-2 text-center">
              “Manage allows us to provide structure and process. It keeps us
              organized and focused. I can’t stop recommending them to everyone
              I talk to!”
            </p>
          </article>
        </div>

        <div className="flex justify-center mt-16">
          <Link href="/">
            <a className="w-36 text-center text-sm py-3 font-medium rounded-3xl bg-BrightRed text-white">
              Get Started
            </a>
          </Link>
        </div>
      </section>

      <section className="bg-BrightRed py-12 mt-10">
        <div className="max-w-6xl mx-auto w-11/12 grid md:grid-cols-2 gap-y-6 items-center">
          <h3 className="w-11/12 text-4xl font-medium text-white">
            Simplify how your team works today.
          </h3>
          <div className="md:justify-self-end">
            <Link href="/">
              <a className="block w-36 text-center text-sm py-3 font-medium rounded-3xl bg-white text-BrightRed">
                Get Started
              </a>
            </Link>
          </div>
        </div>
      </section>

      <footer className="py-16 bg-VeryDarkBlue">
        <div className="max-w-6xl w-11/12 mx-auto grid md:grid-cols-2 lg:grid-cols-[300px_1fr_340px] gap-x-10 gap-y-10 lg:gap-y-0 grid-rows-[auto_auto]">
          <div className="order-4 md:order-none mx-auto md:mx-0">
            <img src="/logo-white.svg" alt="" />
          </div>

          <div className="order-2 px-4 justify-items-center md:justify-items-start grid grid-cols-2 justify-center lg:col-start-2 lg:row-start-1 row-end-3">
            <div className="">
              <Link href="/">
                <a className="block text-white mb-4">Home</a>
              </Link>
              <Link href="/">
                <a className="block text-white mb-4">Pricing</a>
              </Link>
              <Link href="/">
                <a className="block text-white mb-4">Products</a>
              </Link>
              <Link href="/">
                <a className="block text-white">About Us</a>
              </Link>
            </div>
            <div>
              <Link href="/">
                <a className="block text-white mb-4">Careers</a>
              </Link>
              <Link href="/">
                <a className="block text-white mb-4">Community</a>
              </Link>
              <Link href="/">
                <a className="block text-white mb-4">Privacy Policy</a>
              </Link>
            </div>
          </div>
          <div className="order-1 md:order-none">
            <div className="flex">
              <input
                type="text"
                className="block text-sm w-full py-2 px-5 outline-none rounded-3xl border-none"
                placeholder="Updates in your box.."
              />
              <button className="block ml-3 bg-BrightRed px-6 py-3 rounded-3xl text-white text-sm font-medium">
                Go
              </button>
            </div>
          </div>
          <div className="order-3 md:order-none flex justify-center md:justify-start lg:items-end -ml-2 lg:col-start-1 lg:col-end-2">
            <Link href="/">
              <a className="block p-2">
                <img src="/icon-facebook.svg" alt="" />
              </a>
            </Link>
            <Link href="/">
              <a className="block p-2">
                <img src="/icon-youtube.svg" alt="" />
              </a>
            </Link>
            <Link href="/">
              <a className="block p-2">
                <img src="/icon-twitter.svg" alt="" />
              </a>
            </Link>
            <Link href="/">
              <a className="block p-2">
                <img src="/icon-pinterest.svg" alt="" />
              </a>
            </Link>
            <Link href="/">
              <a className="block p-2">
                <img src="/icon-instagram.svg" alt="" />
              </a>
            </Link>
          </div>

          <div className="order-5 md:order-none lg:col-start-3 lg:col-end-4 flex justify-center lg:justify-end items-end">
            <span className="block text-DarkGrayishBlue">
              Copyright 2020. All Rights Reserved
            </span>
          </div>
        </div>
      </footer>
    </>
  );
};

export default Home;
