import React from "react";
import Head from "next/head";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const Layout: React.FC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Landing Manage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <Navbar />
      {children}
      <Footer />
    </>
  );
};

export default Layout;
